### ISSUE TITLE
Ignore Uptime-Kuma/1.21.2

### ISSUE THREAD

**Issue by kaystrobach** [DanielSiepmann/tracking#105]
Uptime-Kuma/1.21.2

is another uptime checker, it should be ignored.

**Comment by DanielSiepmann** [comment]
@kaystrobach thanks, will try to add it this week and provide a new Release.

Would be cool if you could also report at https://github.com/matomo-org/device-detector. I couldn't find it at https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml. And I plan (at some day) to finish the migration to their library. The uptime checker would then be gone.

**Comment by kaystrobach** [comment]
created a related issue

**Comment by DanielSiepmann** [comment]
@kaystrobach looks like there are some breaking changes within testing framework. I need to investigate that beforehand in order to have a passing CI.

**Comment by DanielSiepmann** [comment]
@kaystrobach that's now part of the v2.5.0 version released just now: https://packagist.org/packages/danielsiepmann/tracking
