### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by koritnik** [DanielSiepmann/tracking#72]
Can you please consider the support of PHP 7.2? The current hosting service of some of our clients unfortunately has problems providing a stable PHP 7.3 and PHP 7.4. support. Nevertheless we like to provide the features of your extension. To avoid issues in our deployment setup etc. a PHP 7.2 support would be helpful. We are willing to support this task financially.

**Comment by DanielSiepmann** [comment]
We've looked into other ways for the customer.
Please ping here if the need exists again, or re open.

I'll close for now.
7.2 support mainly has the drawback that we can no longer use latest versions of all the tools, e.g. phpunit.
