### ISSUE TITLE
Ignore Uptimerobot from logging.

### ISSUE THREAD

**Issue by kaystrobach** [DanielSiepmann/tracking#82]
[What is your user agent?](https://uptimerobot.com/#)

The user agent we use is: Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)|

https://uptimerobot.com/faq/

**Comment by DanielSiepmann** [comment]
Thanks, will add this during the DevDays and release an bugfix version :+1:

**Comment by DanielSiepmann** [comment]
Was released: https://packagist.org/packages/danielsiepmann/tracking#v1.2.0 feel free to update and thanks for the addition.
